---
 apiVersion: v1
 kind: Pod
 metadata:
   name: front-end-go
   labels:
     app: go-web
 spec:
   containers:
     - name: front-end-go
       image: apresti12/goapp-hello
       ports:
         - containerPort: 8080